// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/21/2026, 7:52:07 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/yym/Documents/my/projects/instagram/apps/web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yym/Documents/my/projects/instagram/apps/web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yym/Documents/my/projects/instagram/apps/web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yym/Documents/my/projects/instagram/apps/web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yym/Documents/my/projects/instagram/apps/web/app/plugins/**/*.{js,ts,mjs}","/Users/yym/Documents/my/projects/instagram/apps/web/app/composables/**/*.{js,ts,mjs}","/Users/yym/Documents/my/projects/instagram/apps/web/app/utils/**/*.{js,ts,mjs}","/Users/yym/Documents/my/projects/instagram/apps/web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yym/Documents/my/projects/instagram/apps/web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/yym/Documents/my/projects/instagram/apps/web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/yym/Documents/my/projects/instagram/apps/web/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;